### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'drivername'

### ISSUE THREAD

**Issue by sararocha25** [NiketanG/tic-tac-toe-online#158]
hello

I was trying to run your program but i dont know what to set in the enviroment variables

Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    cli() 
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\cli.py", line 440, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "manage.py", line 14, in create_db
    db.create_all()
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\__init__.py", line 1086, in _execute_for_all_tables        
    op(bind=self.get_engine(app, bind), **extra)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\__init__.py", line 593, in get_engine
    sa_url, options = self.get_options(sa_url, echo)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\__init__.py", line 608, in get_options
    sa_url, options = self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask_sqlalchemy\__init__.py", line 933, in apply_driver_hacks
    if sa_url.drivername.startswith('mysql'):
AttributeError: 'NoneType' object has no attribute 'drivername'

**Comment by NiketanG** [comment]
The environment variables 
```
SECRET_KEY=
DATABASE_URI=
```

need to be set before you can run the application. These simply refer to the variables in your operating system.
`SECRET_KEY` is a random string that is used for security purposes, can be set to anything.
`DATABASE_URI` is the path of the database or the connection string used to find and connect your database.

In Windows, these can be set by running the following in the same command prompt as the application, before running the application
```
set SECRET_KEY "some_random_string"
set DATABASE_URI "database connection string"
```

While in Linux and Mac, you can use
```
export SECRET_KEY=some_random_string
export DATABASE_URI=database_connection_string
```

Instead of these steps, you can simply create a file in the application directory with the name `.env`.
The contents of the `.env` file should be as follows:
```
SECRET_KEY=some_random_string
DATABASE_URI=database_connection_string
```

The application will read this file and load the variables and use them.

A sample `.env` file will look something like this
```
SECRET_KEY=0kF003qQ1BFf8SC4FxE8
DATABASE_URI=postgresql://username:password@localhost/tic_tac_toe
```

In the DATABASE_URI, 
`username` refers to the username used to connect to the database, typically `postgres` when using PostgreSQL database. 
`password` is the password for particular user for the database.
`tic_tac_toe` will be the name of your database. 

These variables and format will change based on which database system you are using, for eg. MySQL, MongoDB, etc. 

I suggest reading [this](https://www.geeksforgeeks.org/what-are-environment-variables-in-development/) page for a basic understanding of Environment Variables. 

Closing as I hope this will surely solve your issue. Reopen if you encounter any further issues. 
Thank you.
