### ISSUE TITLE
Cloud

### ISSUE THREAD

**Issue by sararocha25** [NiketanG/tic-tac-toe-online#159]
hi again

how did you deploy this app on the cloud? can you help me please?

thanks

**Comment by sararocha25** [comment]
I already deployed the App to Heroku. But once i click any of the buttons it appears that an error accured, as if the back-end wasnt running.

**Comment by NiketanG** [comment]
You can check the logs for the application to find out the reason behind crash. 
1. Go to your heroku dashboard and select the app.
2.  Click on `More` and select `View Logs`.
3.  Run the application again (either visit the url or Select `Restart all dynos` from previous menu) and grab any logs that appear.

This seems like a configuration issue, most likely Environment Variables.
1. Go to `Settings` tab of application. and click on `Reveal Config Vars`.
2.  In the list that appears, make sure the environment variables from the [Readme](https://github.com/NiketanG/tic-tac-toe-online/blob/main/README.md#how-to-setup) are present.
3. The variables that must be in the list are `SECRET_KEY` and `DATABASE_URI`. You can set the `DATABASE_URI` to the URI of postgresql instance provided by Heroku. Another Variable with the name `DATABASE_URL` should be there, just copy its value and set it to `DATABASE_URL`. Also, make sure the this database connection string starts with `postgresql://`. If it is just `postgres://`, change it to `postgresql://`
5.  After you're done, click on `More` on the top, and select `Restart all dynos`. This will restart the application using new variables, and might take a minute.

**Comment by sararocha25** [comment]
I'm still struggling with these variables. 
In the .env file I added this variables:
 1. SECRET_KEY
 2. DATABASE_URI (`postgresql://`)
 3. DATABASE_URL (`postgres://`) - in **heroku** this variable can't be changed to `postgresql://`
 4. API_URL
 
 I also added this variables to Heroku Config Vars, except API_URL
 
 Do I need to do anything else to make this work? Can you please do a step by step on how to deploy your app?

**Comment by NiketanG** [comment]
You misunderstood me. 
The `DATABASE_URL` in your Heroku Config Vars will refer to the Postgresql Database provided by Heroku for your application. This variable will be like `postgres://some_random_strings`. 

You can notice here that it starts with `postgres` but we need it to be `postgresql`. 

So, just copy whatever the value of `DATABASE_URL` is from heroku config vars. Create a new Config Variable with the name `DATABASE_URI` and paste this value to it. The only change you have to do is change the `postgres` to `postgresql`. Keep the rest of the value as it is. 

If the `DATABASE_URL` already starts with `postgresql` instead of `postgres`, then just copy and paste its value as it is for the `DATABASE_URI` variable. No need to change anything.

For Example.
If the `DATABASE_URL` = `postgres://akjshdaksda:asdasd.amazonaws.com:5432/asdasd`,
copy this value, change the `postgres` to `postgresql` so now it will be 
`postgresql://akjshdaksda:asdasd.amazonaws.com:5432/asdasd`
And now, create a new config variable `DATABASE_URL` and give this value to it. 

I hope this clears up any confusion.

**Comment by sararocha25** [comment]
Here are the config vars i have in Heroku:

![image](https://user-images.githubusercontent.com/61797036/120904331-9c296880-c643-11eb-954c-51b05c91ec59.png)

And the variables in the .env file:

![image](https://user-images.githubusercontent.com/61797036/120904471-5faa3c80-c644-11eb-9ea0-204e70cb1d90.png)

**I already have this way. But heroku only gets the front, and i dont understand why**

**Comment by NiketanG** [comment]
Can you send the logs of your heroku application ? They can be found in More  > View Logs in the dashboard. 
Restart the application using `Restart all dynos` option in the same menu, and then check the logs. Paste them here.

**Comment by sararocha25** [comment]
2021-06-05T21:41:57.692368+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=4&transport=polling&t=NdU81tm&sid=08v12i42v3zeWUaKAAAA" host=jogodogalo.herokuapp.com request_id=71b984eb-6804-4540-aad9-9e6c5673eb06 fwd="23.106.249.35" dyno=web.1 connect=0ms service=2ms status=200 bytes=262 protocol=https
2021-06-05T21:41:57.692386+00:00 app[web.1]: 10.12.100.194 - - [05/Jun/2021:21:41:57 +0000] "POST /socket.io/?EIO=4&transport=polling&t=NdU81tm&sid=08v12i42v3zeWUaKAAAA HTTP/1.1" 200 2 "https://jogodogalo.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
2021-06-05T21:41:58.061205+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=4&transport=polling&t=NdU81tp&sid=08v12i42v3zeWUaKAAAA" host=jogodogalo.herokuapp.com request_id=751781cd-49b7-4a9a-a6cb-cfc8f383594b fwd="23.106.249.35" dyno=web.1 connect=0ms service=2ms status=200 bytes=251 protocol=https
2021-06-05T21:41:58.061233+00:00 app[web.1]: 10.12.100.194 - - [05/Jun/2021:21:41:58 +0000] "GET /socket.io/?EIO=4&transport=polling&t=NdU81tp&sid=08v12i42v3zeWUaKAAAA HTTP/1.1" 200 38 "https://jogodogalo.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
2021-06-05T21:42:00.044615+00:00 app[web.1]: 10.12.100.194 - - [05/Jun/2021:21:42:00 +0000] "GET /socket.io/?EIO=4&transport=polling&t=NdU82GP&sid=08v12i42v3zeWUaKAAAA HTTP/1.1" 200 1 "https://jogodogalo.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
2021-06-05T21:42:00.053230+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=4&transport=polling&t=NdU82GP&sid=08v12i42v3zeWUaKAAAA" host=jogodogalo.herokuapp.com request_id=7cf6bd4d-edfb-42e9-9625-5a92cb87f9eb fwd="23.106.249.35" dyno=web.1 connect=0ms service=791ms status=200 bytes=213 protocol=https
2021-06-05T21:42:21.715023+00:00 heroku[web.1]: Restarting
2021-06-05T21:42:21.722140+00:00 heroku[web.1]: State changed from up to starting
2021-06-05T21:42:22.486372+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-06-05T21:42:22.700839+00:00 app[web.1]: [2021-06-05 21:42:22 +0000] [4] [INFO] Handling signal: term
2021-06-05T21:42:32.022041+00:00 heroku[web.1]: Starting process with command `gunicorn --pythonpath api --worker-class eventlet -w 1 "app:create_app()"`
2021-06-05T21:42:34.918112+00:00 heroku[web.1]: State changed from starting to up
2021-06-05T21:42:34.568409+00:00 app[web.1]: [2021-06-05 21:42:34 +0000] [4] [INFO] Starting gunicorn 20.1.0
2021-06-05T21:42:34.568913+00:00 app[web.1]: [2021-06-05 21:42:34 +0000] [4] [INFO] Listening at: http://0.0.0.0:39178 (4)
2021-06-05T21:42:34.569017+00:00 app[web.1]: [2021-06-05 21:42:34 +0000] [4] [INFO] Using worker: eventlet
2021-06-05T21:42:34.573756+00:00 app[web.1]: [2021-06-05 21:42:34 +0000] [7] [INFO] Booting worker with pid: 7

**Comment by sararocha25** [comment]
`**And as soon as I click Create New Game button:**`

2021-06-05T21:43:16.127041+00:00 app[web.1]: [2021-06-05 21:43:16,126] ERROR in app: Exception on /api/create/game [GET]
2021-06-05T21:43:16.127054+00:00 app[web.1]: Traceback (most recent call last):
2021-06-05T21:43:16.127055+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
2021-06-05T21:43:16.127056+00:00 app[web.1]:     self.dialect.do_execute(
2021-06-05T21:43:16.127056+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
2021-06-05T21:43:16.127057+00:00 app[web.1]:     cursor.execute(statement, parameters)
2021-06-05T21:43:16.127057+00:00 app[web.1]: psycopg2.errors.UndefinedTable: relation "tictactoe" does not exist
2021-06-05T21:43:16.127058+00:00 app[web.1]: LINE 2: FROM tictactoe 
2021-06-05T21:43:16.127058+00:00 app[web.1]:              ^
2021-06-05T21:43:16.127059+00:00 app[web.1]: 
2021-06-05T21:43:16.127059+00:00 app[web.1]: 
2021-06-05T21:43:16.127060+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2021-06-05T21:43:16.127060+00:00 app[web.1]: 
2021-06-05T21:43:16.127060+00:00 app[web.1]: Traceback (most recent call last):
2021-06-05T21:43:16.127061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
2021-06-05T21:43:16.127061+00:00 app[web.1]:     response = self.full_dispatch_request()
2021-06-05T21:43:16.127062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
2021-06-05T21:43:16.127062+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2021-06-05T21:43:16.127062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-06-05T21:43:16.127063+00:00 app[web.1]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-06-05T21:43:16.127063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
2021-06-05T21:43:16.127064+00:00 app[web.1]:     rv = self.dispatch_request()
2021-06-05T21:43:16.127064+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
2021-06-05T21:43:16.127065+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-06-05T21:43:16.127065+00:00 app[web.1]:   File "/app/api/app/game/routes.py", line 28, in create_game
2021-06-05T21:43:16.127065+00:00 app[web.1]:     game = Game.query.filter_by(game_id=game_id).first()
2021-06-05T21:43:16.127066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2750, in first
2021-06-05T21:43:16.127066+00:00 app[web.1]:     return self.limit(1)._iter().first()
2021-06-05T21:43:16.127066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
2021-06-05T21:43:16.127067+00:00 app[web.1]:     result = self.session.execute(
2021-06-05T21:43:16.127067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
2021-06-05T21:43:16.127068+00:00 app[web.1]:     result = conn._execute_20(statement, params or {}, execution_options)
2021-06-05T21:43:16.127068+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
2021-06-05T21:43:16.127068+00:00 app[web.1]:     return meth(self, args_10style, kwargs_10style, execution_options)
2021-06-05T21:43:16.127069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
2021-06-05T21:43:16.127069+00:00 app[web.1]:     return connection._execute_clauseelement(
2021-06-05T21:43:16.127069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
2021-06-05T21:43:16.127070+00:00 app[web.1]:     ret = self._execute_context(
2021-06-05T21:43:16.127070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
2021-06-05T21:43:16.127070+00:00 app[web.1]:     self._handle_dbapi_exception(
2021-06-05T21:43:16.127070+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
2021-06-05T21:43:16.127071+00:00 app[web.1]:     util.raise_(
2021-06-05T21:43:16.127071+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
2021-06-05T21:43:16.127074+00:00 app[web.1]:     raise exception
2021-06-05T21:43:16.127074+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
2021-06-05T21:43:16.127074+00:00 app[web.1]:     self.dialect.do_execute(
2021-06-05T21:43:16.127075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
2021-06-05T21:43:16.127075+00:00 app[web.1]:     cursor.execute(statement, parameters)
2021-06-05T21:43:16.127075+00:00 app[web.1]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "tictactoe" does not exist
2021-06-05T21:43:16.127075+00:00 app[web.1]: LINE 2: FROM tictactoe 
2021-06-05T21:43:16.127076+00:00 app[web.1]:              ^
2021-06-05T21:43:16.127076+00:00 app[web.1]: 
2021-06-05T21:43:16.127076+00:00 app[web.1]: [SQL: SELECT tictactoe.game_id AS tictactoe_game_id, tictactoe.next AS tictactoe_next, tictactoe.board AS tictactoe_board, tictactoe.online AS tictactoe_online 
2021-06-05T21:43:16.127077+00:00 app[web.1]: FROM tictactoe 
2021-06-05T21:43:16.127077+00:00 app[web.1]: WHERE tictactoe.game_id = %(game_id_1)s 
2021-06-05T21:43:16.127077+00:00 app[web.1]:  LIMIT %(param_1)s]
2021-06-05T21:43:16.127077+00:00 app[web.1]: [parameters: {'game_id_1': 96024, 'param_1': 1}]
2021-06-05T21:43:16.127078+00:00 app[web.1]: (Background on this error at: http://sqlalche.me/e/14/f405)
2021-06-05T21:43:16.128968+00:00 app[web.1]: 10.32.238.58 - - [05/Jun/2021:21:43:16 +0000] "GET /api/create/game HTTP/1.1" 500 290 "https://jogodogalo.herokuapp.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"

**Comment by NiketanG** [comment]
This is happening because the table `tictactoe` doesn't exist on your heroku database. It's a very simple fix. Just go to More > Run Console in the heroku dashboard. In the prompt that appears, enter this. 
```
python manage.py create_db
```

This will create the required tables.

**Comment by sararocha25** [comment]
That was it! 😃 Thank you so so much. And sorry for all the questions, you really helped me.

**Comment by NiketanG** [comment]
You're welcome. Glad to be of help.
